### ISSUE TITLE
Test the lastest monkey patching is working

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/st2tests#188]
We desire to add some tests to validate this PR: https://github.com/StackStorm/st2/pull/4976

From the changes in the PR, if possible we should test the monkey patch on the following services: 
- [ ] st2actions/st2actions/cmd/st2notifier.py
- [ ] st2actions/st2actions/cmd/st2resultstracker.py
- [ ] st2auth/st2auth/cmd/api.py
- [ ] st2common/bin/paramiko_ssh_evenlets_tester.py
- [ ] st2exporter/st2exporter/cmd/st2exporter_starter.py
- [ ] st2reactor/st2reactor/cmd/garbagecollector.py
- [ ] st2reactor/st2reactor/cmd/rulesengine.py
- [ ] st2reactor/st2reactor/cmd/sensormanager.py
- [ ] st2reactor/st2reactor/cmd/timersengine.py
- [x] st2reactor/st2reactor/container/sensor_wrapper.py (@punkrokk / @amanda11) 
- [x] ~~st2reactor/tests/unit/test_sensor_wrapper.py~~

I'm not sure we can test all of these. Hopefully @Kami Can shed some light on an approach. Searching the web fails because monkey patch is a common testing strategy.

**Comment by amanda11** [comment]
@punkrokk Do we need a test for the last one? e.g. a test for a test? (st2reactor/tests/unit/test_sensor_wrapper.py!)

**Comment by punkrokk** [comment]
@amanda11 haha, probably not. Sorry

**Comment by punkrokk** [comment]
Closing this as we tested what we know how to and did not get any other responses.
